sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
- mvn clean package -U
- docker build -t asrsa/fs-user .

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push asrsa/fs-user
